updates

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -74,7 +74,7 @@ jobs:
           name: Build and Push Docker Image
           command: |
             # Authenticate with Docker Hub (No TTY issue)
-            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin || { echo "❌ Docker login failed!"; exit 1; }
+            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin 2>/dev/null || { echo "❌ Docker login failed!"; exit 1; }
 
             # Build the Docker image
             docker build -t $DOCKERHUB_USERNAME/waste_detection:latest . || { echo "❌ Docker build failed!"; exit 1; }
